language: php

php:
  - 7.1
  - 7.0
  - 5.6

sudo: false

install: composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - composer quality

after_script: bash <(curl -s https://codecov.io/bash)
